package com.skele.jetpack.data

import androidx.room.Database
import androidx.room.RoomDatabase

/**
 * ### RoomDatabase
 * Database created by android room framework.
 *
 * - In order to work properly, it has to declared as an abstract class.
 * - An Implementation of this abstract class is generated by the framework.
 * - Acquire generated database via #Room.databaseBuilder
 * - Each entity passed becomes a table in the sqlite database.
 *
 * Room 프레임워크에 의해 만들어지는 데이터베이스.
 *
 * - 추상 클래스로 선언되어야하며, 해당 구현체는 프레임워크에 의해 생성된다.
 * - 생성된 구현체는 #Room.databaseBuilder를 통해 사용할 수 있다.
 * - Entity로 선언된 데이터 클래스가 데이터베이스에 테이블로서 생성된다.
 *
 * @see RoomDatabase
 */
@Database(entities = [Memo::class], version = 1)
abstract class MemoDatabase : RoomDatabase() {

    abstract fun memoDao() : MemoDao

}